### ISSUE TITLE
Expose health & metrics endpoints with Spring Actuator

### ISSUE THREAD

**Issue by F1iper** [Dance-reservation-system/Reservation-system#5]
Ensure we have basic operational insight via Actuator.

Implementation details:
- Add Spring Boot Actuator dependency to pom.xml
- In application.yml configure:

``` yaml
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
```

Acceptance criteria:
1. GET /actuator/health -> HTTP 200 { "status": "UP"}
2. GET /actuator/metrics -> HTTP 200 with valid JSON metrics
3. GET /actuator/info -> HTTP 200 with non-empty JSON payload (build-info populated)
